version: '3'
networks:
  dev-net:
    driver: bridge
services:
  react-app:
    container_name: react-app
    build: client
    networks:
      - dev-net
    ports:
      - '3000:3000'
    volumes:
      - ./client/public:/client/public
      - ./client/src:/client/src
  express-app:
    container_name: express-app
    build: server
    networks:
      - dev-net
    ports:
      - '4000:4000'
    environment:
      PORT: '4000'
    volumes:
      - ./server/app:/server/app
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - dev-net
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
  adminmongo:
    container_name: adminmongo
    image: mrvautin/adminmongo
    networks:
      - dev-net
    depends_on:
      - mongo
    environment:
      CONN_NAME: 'mern-stack-connection'
      DB_HOST: 'mongo'
      DB_PORT: '27017'
      HOST: '0.0.0.0'
      PORT: '5000'
    ports:
      - '5000:5000'
volumes:
  mongodata: